
services:
  postgresql:
    env_file: ./.env
    image: postgres:17-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
    ports: 
      - $LOCALPORT:$DOCKERPORT
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
